name: toss_intro
description: "toss style intro screen for flutter"
#publish_to: 'none'
repository: https://github.com/juneview-songdo/toss_intro

version: 1.0.6

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout:
  bot_toast:
  device_preview:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  go_router:
  june:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  styled_widget:
  tuple: #@add
  flutter_color: #@add
  infinite_listview: #@add
  auto_size_text:  #@add

dev_dependencies:
  bot_toast_module:
  device_preview_module:
  flutter_lints:
  flutter_lints_module:
  flutter_test:
    sdk: flutter
  june_view:  #@add
  june_view_more:  #@add
  screenutil_module:

flutter:
  assets:
    - assets/view/toss_intro/
  uses-material-design: true